name: Check pre-commit rules

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  container:
    runs-on: ubuntu-latest
    container: zimkal/qemu2
    steps:
      - run: |
          echo Run QEMU jobs
          pwd
          cd /opt/esp/idf
          . ./export.sh
          pytest --target esp32 -m qemu --embedded-services idf,qemu
        name: Run in container
