name: Check pre-commit rules

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run_hello_world_test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Container
        run: docker pull zimkal/qemu2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch head and base refs
        # This is necessary for pre-commit to check the changes in the PR branch
        run: |
          git fetch origin ${{ github.base_ref }}:base_ref
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_ref
